"""empty message

Revision ID: 0001
Revises: 
Create Date: 2024-03-17 20:03:29.614293

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
                    sa.Column('settlement_symbol', sa.Integer(), nullable=False),
                    sa.Column('name', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('settlement_symbol')
                    )
    op.create_index(op.f('ix_city_settlement_symbol'), 'city', ['settlement_symbol'], unique=False)
    op.create_table('population_by_age',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('city_id', sa.Integer(), nullable=True),
                    sa.Column('data_year', sa.Integer(), nullable=False),
                    sa.Column('data_month', sa.Integer(), nullable=False),
                    sa.Column('range_0_5', sa.Integer(), nullable=False),
                    sa.Column('range_6_18', sa.Integer(), nullable=False),
                    sa.Column('range_19_45', sa.Integer(), nullable=False),
                    sa.Column('range_46_55', sa.Integer(), nullable=False),
                    sa.Column('range_56_64', sa.Integer(), nullable=False),
                    sa.Column('range_65_and_more', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['city_id'], ['city.settlement_symbol'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('date_index', 'population_by_age', ['data_year', 'data_month'], unique=False)
    op.create_index(op.f('ix_population_by_age_id'), 'population_by_age', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_population_by_age_id'), table_name='population_by_age')
    op.drop_index('date_index', table_name='population_by_age')
    op.drop_table('population_by_age')
    op.drop_index(op.f('ix_city_settlement_symbol'), table_name='city')
    op.drop_table('city')
    # ### end Alembic commands ###
